apiVersion: v1
kind: Pod
metadata:
 name: my-app-pod
spec:
 containers:
  - name: my-app
    image: nginx
    ports:
     - containerPort: 8080
    envFrom:
     - secretRef:
        name: app-secret
