apiVersion: v1
kind: Pod
metadata:
 name: my-app-pod
 labels:
  tier: app
spec:
 containers:
  - name: webapp
    image: nginx
    ports:
     - containerPort: 8080
    env:
     - name: APP_COLOR
       value: blue
